[package]
name = "wasm-gif-encoder"
version = "0.1.0"
authors = ["cenfun <cenfun@gmail.com>"]
description = "wasm-gif-encoder"
repository = "https://github.com/cenfun/wasm-gif-encoder.git"
license = ""

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "^0.2.83"
gif = "^0.11.4"
#png = "^0.15.0"
#png-decoder = { git = "https://github.com/mpizenberg/png-decoder" } 

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
lol_alloc = "0.2.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"


